Repository ISPC-TSDW/libroteka-frontend, pull requests merged in 2025-06, with the labels that each got.

#36 26 us02 tk03 la orden de compra queda registrada en la db
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/payment-gateway/payment-gateway.component.html
  src/app/components/payment-gateway/payment-gateway.component.ts
  src/app/components/payment-gateway/success.component.css
  src/app/components/payment-gateway/success.component.html
  src/app/components/payment-gateway/success.component.ts
  src/app/environment.ts
  src/app/services/auth.service.ts
  src/app/services/order.service.ts
  src/index.html
Labels: Tarea, Web

#37 modify login and register
  src/app/components/create/create.component.css
  src/app/components/create/create.component.html
  src/app/components/create/create.component.ts
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/assets/images/icons/visibility_24dp_1A1A1A.svg
  src/assets/images/icons/visibility_off_24dp_1A1A1A.svg
Labels: Funcional, Web

#38 Fixauthor orders
  src/app/components/payment-gateway/payment-gateway.component.html
  src/app/components/payment-gateway/payment-gateway.component.ts
Labels: Web

#40 modify mp, styles, etc.
  src/app/components/create/create.component.css
  src/app/components/create/create.component.html
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/payment-gateway/payment-gateway.component.html
  src/app/components/payment-gateway/payment-gateway.component.ts
  src/app/components/payment-gateway/success.component.ts
  src/app/components/shared/navbar/navbar.component.css
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.ts
  src/app/services/order.service.ts
Labels: Web

#39 Modal libro ad
  src/app/components/admin/admin-books.component.html
  src/app/components/book-details/book-details.component.css
  src/app/components/book-details/book-details.component.html
  src/app/components/book-details/book-details.component.ts
  src/app/components/catalogo/catalogo.component.css
  src/app/components/catalogo/catalogo.component.html
  src/app/components/catalogo/catalogo.component.ts
  src/app/components/inicio/inicio.component.css
  src/app/components/inicio/inicio.component.html
  src/app/components/inicio/inicio.component.ts
  src/app/components/shared/footer/footer.component.css
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/footer/footer.component.ts
  src/app/components/shared/navbar/navbar.component.css
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.ts
  src/app/services/author.service.ts
  src/app/services/book.service.ts
  src/app/services/category.service.ts
  src/app/services/editorial.service.ts
  src/app/services/genre.service.ts
Labels: bug, Web

#43 Feature/favoritos
  src/app/app.routes.ts
  src/app/components/favoritos/favoritos.component.css
  src/app/components/favoritos/favoritos.component.html
  src/app/components/favoritos/favoritos.component.ts
  src/app/services/favorite.service.ts
Labels: Funcional, Web

#34 Dev
  src/app/app.routes.ts
  src/app/components/admin/admin-books.component.html
  src/app/components/book-details/book-details.component.css
  src/app/components/book-details/book-details.component.html
  src/app/components/book-details/book-details.component.ts
  src/app/components/catalogo/catalogo.component.css
  src/app/components/catalogo/catalogo.component.html
  src/app/components/catalogo/catalogo.component.ts
  src/app/components/create/create.component.css
  src/app/components/create/create.component.html
  src/app/components/create/create.component.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/favoritos/favoritos.component.css
  src/app/components/favoritos/favoritos.component.html
  src/app/components/favoritos/favoritos.component.ts
  src/app/components/inicio/inicio.component.css
  src/app/components/inicio/inicio.component.html
  src/app/components/inicio/inicio.component.ts
  src/app/components/landing/landing.component.html
  src/app/components/login/login.component.css
  src/app/components/login/login.component.html
  src/app/components/login/login.component.ts
  src/app/components/payment-gateway/payment-gateway.component.html
  src/app/components/payment-gateway/payment-gateway.component.ts
  src/app/components/payment-gateway/success.component.css
  src/app/components/payment-gateway/success.component.html
  src/app/components/payment-gateway/success.component.ts
  src/app/components/shared/footer/footer.component.css
  src/app/components/shared/footer/footer.component.html
  src/app/components/shared/footer/footer.component.ts
  src/app/components/shared/navbar/navbar.component.css
  src/app/components/shared/navbar/navbar.component.html
  src/app/components/shared/navbar/navbar.component.ts
  src/app/environment.ts
  src/app/models/book.model.ts
  src/app/services/auth.service.ts
  src/app/services/author.service.ts
  src/app/services/book.service.ts
  src/app/services/category.service.ts
  src/app/services/editorial.service.ts
  src/app/services/favorite.service.ts
  src/app/services/genre.service.ts
  src/app/services/order.service.ts
  src/assets/images/icons/visibility_24dp_1A1A1A.svg
  src/assets/images/icons/visibility_off_24dp_1A1A1A.svg
  src/index.html
Labels: Web
